### ISSUE TITLE
Cannot install fisherman

### ISSUE THREAD

**Issue by alexmsmartins** [fisherman/fisherman#166] opened 2016-03-20 00:50 UTC
Here is the shell session where I present all the versions of the necessary software and then try to do an installation. Since I use vim-mode, you can identify the new commands by `[I] ~ $`.
```
[I] ~ $ fish --version
fish, version 2.2.0
[I] ~ $ git --version
git version 2.7.4
[I] ~ $ uname -a
Linux lt15713 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[I] ~ $ tree ~/.config/fish/
/home/alexandre/.config/fish/
├── config.fish
├── config.fish~
├── fishd.f01faf4ed963
├── fish_history
├── fish_read_history
├── functions
│   └── fish_prompt.fish
└── nvm-wrapper
    ├── CODE_OF_CONDUCT.md
    ├── nvm.fish
    └── README.md

2 directories, 9 files
[I] ~ $ tree ~/.local/share/fish/
/home/alexandre/.local/share/fish/
└── generated_completions

1 directory, 0 files
[I] ~ $ vimcat ~/.config/fish/config.fish 

#alex# sbt path
set -x ANDROID_HOME $HOME/adt-bundle-linux-x86_64/sdk
#set -x ANDROID_SDK_ROOT $HOME/adt-bundle-linux-x86_64/sdk
#set -x ANDROID_SDK_HOME $HOME/adt-bundle-linux-x86_64/sd



set -x PATH $ANDROID_HOME/tools:~/node_modules/.bin:~/sbt/bin:~/android-studio/bin:~/bin:$PATH

set -x PATH ~/nodejs/bin:$PATH

set -x PATH ~/bin $PATH

set -x WINDOWS_USER alex.martins

#Linuxbrew
set -x PATH $HOME/.linuxbrew/bin $PATH
set -x MANPATH $HOME/.linuxbrew/share/man (manpath)
set -x INFOPATH $HOME/.linuxbrew/share/info $INFOPATH

set -x PATH ~/.local/lib/aws/bin:$PATH

#AWS CLI autocomplete
#complete -C aws_completer aws

set -x NVM_DIR ~/.nvm
source ~/.config/fish/nvm-wrapper/nvm.fish
nvm use default 1> /dev/null
#[ -s "$NVM_DIR/nvm.sh" ] and . "$NVM_DIR/nvm.sh"  # This loads nvm
# [[ -r $NVM_DIR/bash_completion ]] and . $NVM_DIR/bash_completion

#complete -C '~/.local/lib/aws/bin/aws_completer' aws
set -x PATH $HOME/.local/lib/aws/bin:$PATH

set -x  NEW_RELIC_LICENSE_KEY dddddddddddddddddddddddddddddddddddddd

#UkLive Scripts
set -x PATH $HOME/workspace/UkLive/scripts/helpers:$PATH

set -x VISUAL vim

fish_vi_mode
set -x EDITOR "$VISUAL"

[I] ~ $ curl -sL get.fisherman.sh | fish
manpath: warning: $MANPATH set, ignoring /etc/manpath.config
 × Downloading Fisherman to ~/.local/share/fisherman

Sorry, but I couldn't install Fisherman. Some things you can try:

 → Upgrade your Git version (^2.0)
 → Upgrade your Fish version (^2.2.0)
 → Make sure you can write to 
 → Make sure you are connected to the Internet
```
I could have simplified this but maybe leaving it complete will give someone extra hints about what extra information you need from me.

**Comment by bucaran** [comment] 2016-03-20 01:13
@alexmsmartins Ok, so it seems you couldn't even download Fisherman. Do you have write permissions in `~/.local/share`?

**Comment by alexmsmartins** [comment] 2016-03-20 02:33
Hi @bucaran . I double checked permissions and I do have write permissions to `~/.local/share`. This is inside a regular $HOME directory and I have right permissions everywhere.

**Comment by bucaran** [comment] 2016-03-20 02:44
@alexmsmartins 

In that case, Fisherman must be downloaded to ~/.local/share.

But here is one fun thing you can try:

```
curl -sL get.fisherman.sh | env TRY_ME=true fish
```

Can we troubleshoot this together? [join.fisherman.sh](http://join.fisherman.sh)

**Comment by alexmsmartins** [comment] 2016-03-21 19:58
@bucaran 

I do not see anything strange.

Here is the output

```fish
[I] ~ $ curl -sL get.fisherman.sh | env TRY_ME=true fish
manpath: warning: $MANPATH set, ignoring /etc/manpath.config
# Clone Fisherman repository to XDG_DATA_HOME/fisherman
git clone --quiet --depth 1 https://github.com/fisherman/fisherman /home/alexandre/.local/share/fisherman

# Create Fisherman configuration directories in XDG_CONFIG_HOME/fisherman
pushd '/home/alexandre/.local/share/fisherman'

if test (uname) = 'FreeBSD'
    gmake > /dev/null
else
    make > /dev/null
end

popd

# Download Fisherman index file without a timeout
__fisher_index_update 0

# Install CLI utilities. See github.com/fishery/{spin,debug}
fisher_install 'spin' 'debug' --quiet

# Reload your shell session to make Fisherman immediately available
exec fish < /dev/tty
```

**Comment by bucaran** [comment] 2016-03-22 01:38
@alexmsmartins OK, we are making progress. Fisherman actually runs that exactly. If you try running each of those instructions one by one we could find exactly the place where you are getting stuck.

Start with

```
git clone --quiet --depth 1 https://github.com/fisherman/fisherman /home/alexandre/.local/share/fisherman
```

and let me know what happened.

**Comment by xMrWhite** [comment] 2016-03-22 14:44
I was having this problem today the requirements do not let you know that you are missing make. You should test if make ran and report that as the problem rather than the git and fish versions.

**Comment by jethrokuan** [comment] 2016-03-22 14:45
The curl installer has no dependency on make, just fish and some basic unix
tools like sed.

> On Mar 22 2016, at 10:44 pm, xMrWhite &lt;notifications@github.com&gt;
wrote:  

>

> I was having this problem today the requirements do not let you know that
you are missing make. You should test if make ran and report that as the
problem rather than the git and fish versions.

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/fisherm
an/fisherman/issues/166#issuecomment-199846099)![](https://github.com/notifica
tions/beacon/ABlxkay-ovRcl_5FZT-w9SubVcLnXVubks5pwAA-gaJpZM4H0kcG.gif)

**Comment by xMrWhite** [comment] 2016-03-22 14:47
Are you sure because your commands up there
```
    if test (uname) = 'FreeBSD'
    gmake > /dev/null
else
    make > /dev/null
end
```
run make

**Comment by jethrokuan** [comment] 2016-03-22 14:49
oh wow how'd I miss that. Thanks! :smile:

**Comment by bucaran** [comment] 2016-03-22 14:50
@xMrWhite Oh, so _that_ was the problem! Thanks. This should be easy to check and explain in the troubleshoot report.

https://github.com/fisherman/install/issues/3

**Comment by xMrWhite** [comment] 2016-03-22 14:54
I mean i'm not @alexmsmartins but I was installing fish and fisher only a new ubuntu 14.04 cloud today and got the exact same output  `sudo apt-get install build-essential` made it work. I did not try just installing make.

**Comment by bucaran** [comment] 2016-03-22 14:57
@xMrWhite Yes, and thanks for the solution snippet.

**Comment by alexmsmartins** [comment] 2016-03-22 23:19
@bucaran 

Running the commands one by one works with a little tweak. Basically, I need to reload the shell before running `__fisher_index_update`.  

Here is the shell session.
```fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
[I] ~ $ fisher
fisher: command not found
[I] ~ $ git clone --quiet --depth 1 https://github.com/fisherman/fisherman /home/alexandre/.local/share/fisherman
[I] ~ $ pushd '/home/alexandre/.local/share/fisherman'
[I] ~/.l/s/fisherman (master) $ make # I want to see the output
mkdir -p $HOME/.config/fish/ && touch $HOME/.config/fish/config.fish
echo "set fisher_home /home/alexandre/.local/share/fisherman/" | sed "s|/$||;s|$HOME|~|" > $HOME/.config/fish/config.fish.fisher
echo "set fisher_config $HOME/.config/fisherman" | sed "s|$HOME|~|" >> $HOME/.config/fish/config.fish.fisher
echo "source \$fisher_home/config.fish" >> $HOME/.config/fish/config.fish.fisher
awk 'FNR==NR{ print; a[$0]; next } !($0 in a) || /^$/' $HOME/.config/fish/config.fish $HOME/.config/fish/config.fish.fisher > $HOME/.config/fish/config.fish.tmp
mv $HOME/.config/fish/config.fish.tmp $HOME/.config/fish/config.fish && rm $HOME/.config/fish/config.fish.fisher
mkdir -p $HOME/.config/fisherman/cache
touch $HOME/.config/fisherman/fishfile
** Reload your shell and type 'fisher' to get started **
[I] ~/.l/s/fisherman (master) $ popd
[I] ~ $ __fisher_index_update 0
__fisher_index_update: command not found
[I] ~ $ exec fish < /dev/tty
manpath: warning: $MANPATH set, ignoring /etc/manpath.config
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
[I] ~ $ __fisher_index_update 0
[I] ~ $ fisher_install 'spin' 'debug' --quiet
[I] ~ $ exec fish < /dev/tty
manpath: warning: $MANPATH set, ignoring /etc/manpath.config
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

I have fisherman installed now but if you want me to run any more experiments, let me know.

**Comment by jimfleming** [comment] 2016-03-24 05:38
Just wanted to add that I ran into the same issue as @alexmsmartins. To fix it I ran the steps from `TRY_ME` but reloaded the fish config before running any of the fisher commands. Seems to work now.

**Comment by bucaran** [comment] 2016-03-24 05:38
@jimfleming Hey, thanks, what was the OS in your case?

**Comment by jimfleming** [comment] 2016-03-24 05:57
I edited my original post shortly after hitting enter. Here's the full OS version: OS X (El Capitan) 10.11 (15A284).

**Comment by bucaran** [comment] 2016-03-24 05:59
@jimfleming Do you have `make`? Try `make -v`.

**Comment by jimfleming** [comment] 2016-03-24 06:02
Yup, here's the output:

```
GNU Make 3.81
# license omitted
This program built for i386-apple-darwin11.3.0
```

**Comment by bucaran** [comment] 2016-03-24 07:12
In that case the problem was not `make`. I understand that @alexmsmartins's problem (or maybe that was @xMrWhite or someone else) was they didn't have `make`.

Well, I am going to close this as resolved, since all of you were able to install Fisherman correctly, but do please ping me if you try to re-install Fisherman and something does not go well as I was not able to reproduce this problem in two different macs.

**Closed by bucaran** 2016-03-24 07:12 UTC
Labels: SUPPORT
