### ISSUE TITLE
Archlinux package

### ISSUE THREAD

**Issue by mkaito** [fisherman/fisherman#160] opened 2016-03-17 10:13 UTC
Anyone can contribute packages to the [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository#Sharing_and_maintaining_packages). I would really appreciate a package for fisherman. The link explains how it can be done.

**Comment by bucaran** [comment] 2016-03-17 10:17
@mkaito That would be sweet.

Ping @jethrokuan

**Comment by jethrokuan** [comment] 2016-03-17 10:24
@mkaito I'll get on it (:

**Comment by mkaito** [comment] 2016-03-17 10:24
Awesome :smile:

**Comment by jethrokuan** [comment] 2016-03-17 13:10
@mkaito do you have experience making AUR packages? maybe we could do a bit of pair programming. (:

**Comment by mkaito** [comment] 2016-03-17 13:16
Yes, I maintain a bunch of packages. I'd have made it myself already, but I don't want to overburden myself with the maintenance work.

**Comment by jethrokuan** [comment] 2016-03-17 13:18
@mkaito are you on our slack? we could chat about it.

**Comment by jethrokuan** [comment] 2016-03-17 13:52
@mkaito I have something preliminary up [here](https://github.com/jethrokuan/fisherman-aur). The installation works, but I'm having troubles trying to figure out how to uninstall this thing with `pacman -R`. Would be great if you could advise me on this.

**Comment by mkaito** [comment] 2016-03-17 14:07
I'm not on your slack. Are you on Freenode by any chance? Just `/query mkaito`. I use a bouncer, so if I'm marked as away, I'm probably not home.

Re: PKGBUILD

You probably want the `make` call to place files in `$pkgdir`, duplicating the root file system structure. So `/usr/bin/foo` would need to be placed in `$pkgdir/usr/bin/foo`. After that, pacman should be able to take care of file management just fine.

**Comment by bucaran** [comment] 2016-03-17 14:27
@mkaito If you have the Slack application you are welcome aboard [join.fisherman.sh](http://join.fisherman.sh).

**Comment by pickfire** [comment] 2016-03-17 15:11
I have some experience creating packages but I don't have any experience uploading those build files to arch linux, I guess @mkaito can really do a good job here.

**Comment by mkaito** [comment] 2016-03-18 02:51
It works through git. Each package is a magic gitoliite repo. You just clone it to create it. The process is described in the wiki page I linked above.

If you need a hand, I can pop into slack. @jethrokuan poked me on IRC, but caught me during my nap time (sorry :stuck_out_tongue:)

**Comment by bucaran** [comment] 2016-03-24 12:04
@mkaito @pickfire @jethrokuan Any updates on this?

**Comment by pickfire** [comment] 2016-03-24 13:53
@bucaran Not sure, I am not working on this. I guess @mkaito knows more.

**Comment by jethrokuan** [comment] 2016-03-24 13:53
Tried to tackle this, was not successful.

**Comment by mkaito** [comment] 2016-03-24 14:03
I haven't done any work on this so far, but I'll try to write a PKGBUILD as soon as I have some time. I'll bug you on Slack if I need help correctly placing files.

IMHO, it should be a repo under the fisherman organization that mirrors the AUR repo, so that it can be maintained by the community via pull request.

**Comment by jethrokuan** [comment] 2016-03-24 14:37
@mkaito thanks for taking this up. Adding the repo to the organization would be no problem.

**Comment by mkaito** [comment] 2016-03-24 14:39
I'll create the repo and transfer it when I'm done.

**Comment by bucaran** [comment] 2016-03-24 14:42
@mkaito Thanks! :heart:

**Comment by jethrokuan** [comment] 2016-03-26 07:06
@mkaito https://aur.archlinux.org/packages/fisherman-git/

This was created by @orangecms , any comments?

**Comment by jethrokuan** [comment] 2016-03-26 07:08
For one, fisherman uses git internally to install and update plugins, so git should merely be a dependency to build the package.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fisherman-git#n12

**Comment by mkaito** [comment] 2016-03-26 08:26
That looks fine to me. Seems to put things in the right places, at least. If git is used at runtime, it needs to be made a dependency rather than a build-time dependency, though. I've pointed the maintainer at this issue for discussion.

**Comment by orangecms** [comment] 2016-03-26 19:43
I just saw your comment in the AUR. So, the `make` cannot be used. It doesn't actually *work* if you put that in a PKGBUILD. It only circumvents pacman. Like @mkaito described, a Makefile should create a directory structure that allows installing to a prefix. @mkaito we have been discussing quite a lot on Slack already, and I wouldn't see a problem doing that in IRC as well, but then again... we would have 4 places already: AUR comments, GitHub, Slack, and IRC. As this concerns also packaging for other distros/systems, I think the discussion really belongs here, so let's keep it here.

I have been chatting with @bucaran about the installation procedure, and he would like to keep it the way that Fisherman rewrites a user's config file. I think that is against their consent, and we couldn't find an agreement here. For the AUR package, I have now created another config file that can simply be sourced and respects a user's preferences for the `fisher_home`/`fisher_config` vars, or uses the usual defaults. In the post install hook, I provide a hint telling the user how to include it (it's only one line then). That's similar to how I did it in https://aur.archlinux.org/packages/vim-dein-git/ and how Vundle recommends installation.

**Comment by bucaran** [comment] 2016-03-26 19:53
FTR I am entirely open to modify how the Fisherman installation works. Rewrite the config.fish, do not rewrite it, all works. :smile: 

What I'd like to see is some actual code, in the form of a PR or a gist that shows with code how things will look like so that I can figure out how I would need to modify the [external](https://github.com/fisherman/install) installer in order to continue to support one line magic installers like the one a lot of people seem to favor.

**Comment by bucaran** [comment] 2016-03-29 12:54
@orangecms Can we close this or is the package still WIP?

**Comment by jethrokuan** [comment] 2016-03-29 13:04
@orangecms installed the AUR package, and faced some issues, mainly because you don't copy everything in. The VERSION file is important for fisherman to update, for example. I foresee issues downloading the index as well, although I didn't go this far.

**Comment by orangecms** [comment] 2016-03-29 17:57
Updating system packages is the sole responsibility of the system's package manager. The package would test and choose the current version. Or in this case, as it is a git package, it will always be fetched from the repo. So you would e.g. `pacaur -S fisherman-git` or whatever AUR helper you use to update. Is the index stored in the home or config dir? It should be in config, as the user deals with it.

**Comment by bucaran** [comment] 2016-03-29 18:00
The index is in the config, yes.

**Comment by orangecms** [comment] 2016-03-29 18:02
@bucaran the package is there so far, so I'd say the issue is resolved. It may still undergo improvements or changes depending on the development of Fisherman. But I would rather like @mkaito to have a final word on it and close it himself then.

**Comment by mkaito** [comment] 2016-03-30 00:28
As far as I can tell, the package works. I still think there should be a mirror of the AUR repo here on Github, under the fisherman organization. @orangecms may continue to update the AUR repo itself, but Github is pretty useful for issues and contributions.

**Comment by orangecms** [comment] 2016-03-30 06:30
Sure, I can just put it here as well. Before Arch switched to Git repos for AUR I versioned my PKGBUILDs on my other GitHub account https://github.com/cyrevolt - now thinking that I don't need it anymore because web have Git in AUR I haven't touched it for a while though. You can always clone the repo yourself anyway. I wouldn't want to keep duplicates if the same repo updated though (I know you can do it automatically, it just seems pointless to me unless you actually fork and diverge).

**Comment by jethrokuan** [comment] 2016-03-30 08:39
To paraphrase,  if someone installs fisherman with the AUR package and runs
`fisher u` and sees "could not update fisherman",  this is expected
behavior and people would be okay with that? `fisher u` is also the
mechanism for updating all plug-ins, and I think it's by far my most run
fisher command, so I don't think having it broken in AUR installs is a good
idea.

**Comment by bucaran** [comment] 2016-03-31 13:22
Hi @denji, perhaps you could help us write the brew formula when the new installation mechanism is merged?

**Comment by orangecms** [comment] 2016-04-01 00:35
@jethrokuan It isn't broken in AUR installs. You can always update to the latest version through your preferred AUR helper or by makepkg if you download the tarball/PKGBUILD. You just don't have write permissions to /usr/share. The update mechanism of Fisherman shouldn't update Fisherman though, as the description says that it only updates the plugins. Other plugin/package managers have a flag like --self-update for that purpose.

**Comment by jethrokuan** [comment] 2016-04-01 01:49
```
jethro@jethroksy ~/D/Source> cd fisherman-git/
jethro@jethroksy ~/D/S/fisherman-git> makepkg -sri
==> Making package: fisherman-git 1.3.1.r19.g88b0e6e-4 (Fri Apr  1 09:47:35 SGT 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning fisherman git repo...
Cloning into bare repository '/home/jethro/Documents/Source/fisherman-git/fisherman'...
remote: Counting objects: 1998, done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 1998 (delta 31), reused 0 (delta 0), pack-reused 1899
Receiving objects: 100% (1998/1998), 802.76 KiB | 208.00 KiB/s, done.
Resolving deltas: 100% (1127/1127), done.
Checking connectivity... done.
  -> Found config-fisherman.fish
==> Validating source files with sha512sums...
    fisherman ... Skipped
    config-fisherman.fish ... Passed
==> Extracting sources...
  -> Creating working copy of fisherman git repo...
Cloning into 'fisherman'...
done.
==> Starting pkgver()...
==> Updated version: fisherman-git 1.4.0.r0.gc5c1361-1
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "fisherman-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: fisherman-git 1.4.0.r0.gc5c1361-1 (Fri Apr  1 09:47:43 SGT 2016)
==> Installing package fisherman-git with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) fisherman-git-1.4.0.r0.gc5c1361-1

Total Installed Size:  0.14 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) installing fisherman-git                     [######################] 100%

To use Fisherman, source it in your fish config (usually ~/.config/fish/config.fish):

source /usr/share/fish/config-fisherman.fish

Please note that Fisherman overrides the config_fish function, so if you also do that,
you will need to do so after sourcing Fisherman.

See the documentation at https://github.com/fisherman/fisherman/wiki for more details.

jethro@jethroksy ~/D/S/fisherman-git> fish
jethro@jethroksy ~/D/S/fisherman-git> fisher l
jethro@jethroksy ~/D/S/fisherman-git> fisher install z
Installing plugin/s
      z                   
1 plugin/s installed (3s)
jethro@jethroksy ~/D/S/fisherman-git> fisher u
cat: /usr/share/fish/../fisherman/VERSION: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
fisher: I couldn't update Fisherman
```

**Comment by jethrokuan** [comment] 2016-04-01 01:50
@orangecms the update mechanism updates fisherman, then updates all plugins.

**Comment by orangecms** [comment] 2016-04-01 07:17
That should be changed. It should only update the plugins, as it says in the menu. We should not assume that fisher_home is writable.

**Comment by bucaran** [comment] 2016-04-01 07:36
@orangecms Sure. We can totally change that after we have a working install process, docs and installer.

**Comment by bucaran** [comment] 2016-04-19 08:14
@jethrokuan @orangecms @mkaito What's the status of this? and does the new install script changes anything?

**Comment by jethrokuan** [comment] 2016-04-19 08:39
@bucaran no, the it's likely that the make script will be used for arch installs.

**Comment by orangecms** [comment] 2016-04-19 09:19
Only if it does what it's supposed to do.

**Comment by bucaran** [comment] 2016-04-19 09:30
@mkaito Maybe you would be more intereted in fin? I think creating an AUR for fin would be way easier than fisherman, maybe we can work on it together?

**Comment by orangecms** [comment] 2016-04-19 09:38
@bucaran you'd just need to install your fish function to `$pkgdir/usr/share/fish/functions`, that's done in a minute. You can copy the PKGBUILD from fisherman-git and simply adjust the metadata. `makepkg` does everything else automatically. ;

**Comment by bucaran** [comment] 2016-04-19 10:21
I want to, but I am not familiar with any of those tools.

**Comment by dalln1** [comment] 2016-04-19 11:53
@bucaran @orangecms I can do a PKGBUILD for fin, will be my first one, but doesn't look to complicated.

**Comment by pickfire** [comment] 2016-04-19 12:43
@bucaran I hope for unlimited time too... :cry:

@dalln1 @bucaran I would like to see a PKGBUILD for fin too but I think we should put it in a seperate place compare in maybe another branch or another repo, I don't think it is wise to enlarge the size of the repo for just simple things.

**Comment by bucaran** [comment] 2016-04-19 12:50
@dalln1 Thanks, that would be awesome 😄

**Comment by jethrokuan** [comment] 2016-04-20 01:16
@bucaran the behaviour of `fisher u` still updates fisherman, and the same goes with fin. This runs contrary to how packages in the AUR should work.

**Comment by bucaran** [comment] 2016-04-20 01:28
@jethrokuan In the case of fin, however, modifying or making a compromise there would be a trivial thing to do.

**Comment by jethrokuan** [comment] 2016-04-20 01:37
@bucaran sure, but this still affects the viability of fisherman living in the AUR.

**Comment by bucaran** [comment] 2016-04-20 01:43
Right. Modifying fisherman to work with AUR is what I was hoping @orangecms would help us with.

I will accept any PR that does it.

WRT to fin, I can modify it to comply with any AUR requirements. Due to its unique update nature, essentially curl and no git, this should be very easy to accomplish.

**Comment by jethrokuan** [comment] 2016-04-20 01:56
@bucaran that would entail removing any means of updating fisherman through the cli, which would affect other users.

**Comment by bucaran** [comment] 2016-04-20 02:10
@jethrokuan Yeah, I am open to any modifications wrt to this if that means making fisherman available in AUR.

**Comment by orangecms** [comment] 2016-04-20 07:46
Yea, fisherman must not update itself. That is the system package manager's job. This is nothing to do with AUR. It's a general thing. Nothing must tamper with the system. I repeat myself: `fisher u` should only update the plugins as that is what it says in the menu. Just behave like other plugin/package managers.

**Comment by bucaran** [comment] 2016-04-20 08:36
Totally agree and I thought you were working on a PR for this.

For my full answer see #201.

**Comment by pickfire** [comment] 2016-04-20 09:46
@orangecms But isn't `fisherman` is just like one package manager like `pacman`? So it should really update any package now right?

> Nothing must tamper with the system.

`fisher i` or `fisher u` will tamper with the system by adding an add-on.

**Comment by bucaran** [comment] 2016-04-20 10:08
@pickfire Yeah, but fisherman is unlikely to be distributed bundled with fish, so that's where we draw the line. fisherman takes care of your user owned addons (all of them are used owned) and a third party, brew, etc., should be responsible for getting fisherman / fin into our system.

**Comment by orangecms** [comment] 2016-04-20 16:19
@pickfire fisherman should only install/update things in the user's home directory. It is not a system package manager like pacman (otherwise that would collide, multiple system package managers will only cause trouble).

**Comment by bucaran** [comment] 2016-04-22 06:14
fisherman 2.0 does not self-update anymore if a non-standard setup is detected, that is, any setup  other than the one advised in the README. So, while the self-upgrade functionality is still there, it does not / will not interfere with AUR or any other package manager AFIK.

**Comment by orangecms** [comment] 2016-04-22 11:26
I'll create a non-git package in AUR. Users of the current -git version will be hinted that Fisherman has changed a lot and they need to take care of an update.

**Comment by bucaran** [comment] 2016-04-23 16:22
@jethrokuan Would you mind having another look at this? I think I could help.

**Comment by bucaran** [comment] 2016-04-24 05:56
https://aur.archlinux.org/packages/fisherman

Big thanks to @orangecms!

I think we can close this now.

**Closed by bucaran** 2016-04-24 05:56 UTC
Labels: HELP, TALK

**Comment by timofonic** [comment] 2017-09-01 14:25
@orangecms  I tried to send you a memo over freenode, but you didn't connect since over 6w ago (if your nickname is cyrevolt)

You need to change in fisherman-git package the LICENSE references to LICENSE.md

https://aur.archlinux.org/packages/fisherman-git

I sometimes stay at #archlinux-aur because I try to maintain linux-drm-tip-git (required to get latest drm changes and debug intel gfx bugs I have).

I mention @ghost just to be somewhat sure more than one person reads this.

Thanks in advance
