### ISSUE TITLE
Fisherman install script fails on Alpine Linux

### ISSUE THREAD

**Issue by herrbischoff** [fisherman/fisherman#184] opened 2016-04-04 00:54 UTC
I was just testing whether my Dotfiles setup would transfer smoothly over to a new system, so I spun up a Docker container with Alpine Linux. Installation of Fisherman did not work. Here's what I did inside the container (`/ #` is the default prompt):

```
/ # apk update
/ # apk add git coreutils
/ # curl -sL get.fisherman.sh | fish
 ✓ Downloading Fisherman to ~/.local/share/fisherman
 × Creating the configuration in ~/.config/fisherman

Sorry, but I couldn't install Fisherman. Some things you can try:

 → Upgrade your Git version (^2.0)
 → Upgrade your Fish version (^2.2.0)
 → Make sure you can write to
 → Make sure you are connected to the Internet

For more help visit http://issues.fisherman.sh
```

Weird, since:

```
/ # git --version
git version 2.6.6
/ # fish --version
fish, version 2.2.0
```

Alpine Linux uses `busybox` as a lightweight shell but I cannot imagine that being a problem. I also tried it in a fresh Ubuntu 14.04 install. After having to upgrade `fish` and `git` manually to their latest versions, the installation still refuses to work, outputting the exact same messages as above.

**Comment by herrbischoff** [comment] 2016-04-04 01:07
Found the problem: `make` needs to be installed. There is currently no check in the install script to account for that.

**Comment by jethrokuan** [comment] 2016-04-04 01:23
@herrbischoff yes, we're considering moving off make for the curl installation, because `make` is really not needed. I think we'll keep this open until that is resolved.

ping @bucaran

**Comment by herrbischoff** [comment] 2016-04-04 01:27
Just submitted a pull request to check for make. May be something for the meantime.

https://github.com/fisherman/install/pull/4

**Comment by bucaran** [comment] 2016-04-04 01:28
Totally. @orangecms do you think we can get a rebased, complete PR addressing #174 and #173. I can't just merge them in their current state. Once that's out of the way, I can create a new curl installer to work with the new make.

**Comment by bucaran** [comment] 2016-04-09 02:11
@herrbischoff So, the problem is Alpine Linux does not come with make. Is that it?

**Comment by herrbischoff** [comment] 2016-04-10 21:31
@bucaran: Unfortunately not. In Ubuntu that's what the problem was. In Alpine Linux it has to be something else. I'm going to investigate further.

**Comment by bucaran** [comment] 2016-04-17 06:38
We should be able to close this when the new installer ships with 1.5.0, which should happen sooner than you expect 😄

**Comment by bucaran** [comment] 2016-04-18 16:01
1275b68e52cfe06937bb7b0c458b6c3e0b916c62

**Closed by bucaran** 2016-04-18 16:01 UTC
Labels: BUG
