### ISSUE TITLE
Absolute paths in links

### ISSUE THREAD

**Issue by nyarly** [fisherman/fisherman#305] opened 2016-06-01 18:23 UTC
I'm using a dotfiles manager to coordinate my fish configuration between Linux and OS X. The trouble is that:

on the one hand, fisher builds links from $HOME/.config/fish/ to $HOME/.config/fisherman using absolute paths (and so /home/nyarly and /Users/nyarly clash),

on the other, running `fisher` doesn't detect the broken links to correct them.

Using relative links seems like the safest solution (e.g. ../../../fisherman/), with ~ paths being second best, but treating broken links as something to fix would be a good thing.

**Comment by brj** [comment] 2016-06-01 18:37
@nyarly I am here scratching my head trying to understand the problem, but my brain is not responding well. AFIK, and in a nutshell, fisherman creates soft links of .fish files in:

* ~/.config/fisherman/plugin_name/{functions,completions,conf.d}
* *into* $fish_path/{functions,completions,conf.d}

where $fish_path is ~/.config/fish by default (but can be configured in that variable).

And wrt to broken links, I have no idea what broken links are those.

**Comment by nyarly** [comment] 2016-06-01 18:54
For instance, when fisherman creates a soft link  `~/.config/fish/functions/z.fish`, the target it uses is something like `/Users/nyarly/.config/fisherman/fasd/functions/z.fish`

When I commit my dotfiles to git and ship them to my linux machine, now `z` doesn't work because z.fish is `file not found` - which is true: I don't have `/Users/nyarly` on my Linux machines, I have `/home/nyarly`.

As a workaround, I've relinked all the symlinks in functions, completions and conf.d to `../../../fisherman`(something) which would be a B- solution for fisherman itself to provide since, as you say, the locations of all these files are configurable.

The other piece is that the tool I use to manage my dotfiles allows for "fixup" commands, and for that I simply run `fisher` which I think does what I want it to do. If fisherman checked the symlinks it *would* make versus the ones that are there and re-linked if there were missing/wrong links (while retaining the copy-old.fish behavior for regular files), I think that'd be ideal. I might need to add gitignores for the functions that fisherman maintains, just to cope with the churn of fisherman changing the links on each side but that'd be acceptable.

Does that all make more sense?

**Comment by brj** [comment] 2016-06-01 19:45
@nyarly Thanks! I think I understand the first part of the issue now.

I think what you should be committing to git is the `fishfile` and not the $fish_path. Then when you switch machines, you pull from your dotfile repo to synchronize the `fishfile` with whatever you used last in the previous machine and run `fisher`.

**Comment by nyarly** [comment] 2016-06-01 20:07
The problem with that is that I tend to write quite a few one-off scripts for fish, and I *do* want to commit them. If I'm very careful only ever to commit the fishfile and my own work, I can probably make do, since fisherman will checkout (any) new plugins and create their links when new entries arrive.

Fixing the links as part of running `fisher` would be a huge reduction of annoyance if/when I miss a linked file, though. Is there a problem with the idea?

**Comment by brj** [comment] 2016-06-02 00:27
@nyarly 
> The problem with that is that I tend to write quite a few one-off scripts for fish, and I do want to commit them

What I do, is that I manage those scripts with fisherman as a local file system plugins, **but** you don't have to change your workflow if you use a $fish_path.

```fish
set -U fish_path ~/my/prefix
```

> Fixing the links as part of running fisher would be a huge reduction of annoyance if/when I miss a linked file, though. Is there a problem with the idea?

Not a problem at all. If I can manage to reproduce what you are seeing here, I would be delighted to offer a solution.

What do I need to do to reproduce a state similar to yours?

**Comment by nyarly** [comment] 2016-06-02 17:10
I think the easiest way would be: create a second user on your computer. Given that your fish/fishfile stuff is set up normally (i.e. no fish_path), copy `~normal_user/.config` to `~test_user/.config` and try using a fish-provided function as the test_user. Given that the test_user doesn't have read access to ~normal_user's homedir, the links should all be broken, but fixable.

**Comment by brj** [comment] 2016-06-02 21:57
I don't understand, do you have multiple users in your computer?

**Comment by daenney** [comment] 2016-06-02 22:23
So, the way I see it fisherman is doing the right thing. The locations are reconfigurable hence relative paths won't work for us in general, they have to be absolute. Hence use the fishfile and have your dotfile manager run `fisherman install` for you instead.

Now, for the one-off scripts I don't understand the problem. If you just drop them into `.config/fish/{conf.d, functions, completions.d}` they'll work once checked into a repository as there is no symlinking going on.

**Comment by nyarly** [comment] 2016-06-03 00:40
@brj The exact use case is as described above: create a git repo for .config/fish and .config/fisherman so that you can check it out onto a different computer where your home directory is different. The reason the files are in a different location seem immaterial to the problem, though, and a solution that involved a single computer seemed easier to reproduce/debug.

@daenney Ultimately, all I'm looking for is that `fisher` or `fisher install` would ensure that links between `.config/fish/` and `.config/fisherman` are correct - and fix them if they're not. It looks like if the plugins are deleted where the dotfiles are being updated, then `fisher` does the right thing, but it leaves links for existing plugins alone (even if they reference non-existent paths)

**Comment by brj** [comment] 2016-06-03 00:50
> **@nyarly**: ...so that you can check it out onto a different computer where your home directory is different.

Ah, I missed this bit. I see. The problem is you are committing your functions directory to git and that includes symlinks to nothing, right?

**Comment by brj** [comment] 2016-06-03 00:53
I think the solution is to use either a $fish_path or do as fin, instead of creating symlinks, create hardlinks. That way it would work even if you _don't_ use $fish_path.

**Comment by nyarly** [comment] 2016-06-03 07:00
What I was thinking is this: in order to do its symlinking, `fisher` needs to compute the target path anyway. What if, at the end of doing `fisher install`, all the links for all plugins got re-created? In the usual case this should be a quick no-op, and it covers this use case completely.

If that's acceptable, I'm more than happy to do the PR.

**Comment by brj** [comment] 2016-06-03 07:05
@nyarly Before you do, can you take a look at #307?

**Comment by brj** [comment] 2016-06-03 13:26
@nyarly I decided to drop the proposal in #307, so by all means feel free to send a PR covering your fixes and let's review it then.

**Closed by brj** 2016-06-03 13:26 UTC
Labels: TALK
